#!/usr/bin/env python
import os
import sys
from djangosite.settings import ON_OPENSHIFT
from djangosite.wsgi import application as wsgi_app


if ON_OPENSHIFT:
    sys.path.append(os.environ['OPENSHIFT_REPO_DIR'])
    virtenv = os.environ['VIRTUAL_ENV']
    os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python3.3/site-packages')
    virtualenv = os.path.join(virtenv, 'bin/activate')
    # noinspection PyBroadException
    try:
        os.system(virtualenv)
    except:
        pass


application = wsgi_app